### ISSUE TITLE
Some lost cells of 3d Delaunay (reopened)

### ISSUE THREAD

**Issue by zmorris** [Scrawk/Hull-Delaunay-Voronoi#7]
The [lost cells issue](https://github.com/Scrawk/Hull-Delaunay-Voronoi/issues/6) is still present. See my comment at https://github.com/Scrawk/Hull-Delaunay-Voronoi/issues/6#issuecomment-478366040 for more information. I'd vote to reopen that issue and continue the conversation there since it has the all the context about it. Sorry to be the bearer of bad news, because otherwise this library seems really advanced!

**Comment by Scrawk** [comment]
This is just some code I played around with 2 years ago and have not touched since.

If your looking for a fix you are not going to find one here. I would recommend just using MIConvexHull. This is just my hack up version of it any way so best to go with the original. For 3D delaunay triangulation to be added to MIConvexHull all you need is the code to calculate the cirumsphere which can be found in this project.

**Comment by zmorris** [comment]
Hey thanks for your quick response on this. Ya I've been looking through MIConvex Hull and might adapt it for my use case.

For anyone who finds this, I think the problem is maybe due to https://github.com/Scrawk/Hull-Delaunay-Voronoi/blob/514465ecd93c5e654d7cd66675c1f4c574021dde/Assets/HullDelaunayVoronoi/Scripts/Hull/ConvexHull.cs#L33

For a test triangulating random vertices in a cube with bounds +/- 1, when I try values like `1e-1f` through `1e-6f` it seems to work. Although curiously a tolerance of `1` or larger seems to fail, as well as `1e-7f` or smaller.

So a viable heuristic might be to set the tolerance to about 1/10,000th the largest vertex axis extent in the mesh around its center. It would also be nice if that constant was changed to an optional parameter.

Hope this helps someone.

**Comment by Scrawk** [comment]
Before you go I should mention that the tolerance is from MIConvexHull and you will find the same issue although I stupidly changed my version to use float instead of double so that may also be a problem.

In the latest version of MIConvexHull the default value is 1e-10 and it is implemented as optional. If set to high the the algorithm will miss identify vertices as being on the same plane and if set to low you get precision issues.

If you are having this issue its normally because some of your vertices are to close and/or spread over too large a distance. I normally round their positions to around 3 decimal places. There maybe other situations where this is a issue that I am not aware of.
